_target_: aita.energies.alp_energy.ALPEnergy
_partial_: true
data_path: ${paths.data_dir}
pdb_filename: alanine_tripeptide.pdb
dimensionality: 99
n_particles: 33
spatial_dim: 3
energy_batch_size: 10000