_target_: aita.models.atomic_transformer_flow.AtomicTransformerFlow
node_feats_in: null
edge_feats_in: null
c_atoms: 256
c_pairs: 128
n_heads: 8
n_layers: 12
dropout_prob: 0.1
bias: False
initial_norm: True